### ISSUE TITLE
Model.ts

### ISSUE THREAD

**Issue by MorganaLF** [RomKmeister/Slider#11]
![Снимок экрана от 2020-07-19 22-14-27](https://user-images.githubusercontent.com/38564412/87883044-3cb37180-ca0d-11ea-9b1e-dfb62d7dccb4.png)

Во-первых, мне кажется, что если вдруг нужно задисейблить правило, то лучше его дисейблить для конкретной строки, а не для всего файла. Можно же случайно потом пропустить и то, что надо было пролинтить.

Но тут что-то вообще интересное происходит: если убрать первое задисейбленное правило, линтер ничего не подсвечивает, хотя последний метод `calculateRatios` должен подсветиться. 

Для чего тут `no-param-reassign`, я что-то не нашла.

**Comment by MorganaLF** [comment]
А что здесь за странная проверка, какая длина может быть у Object.keys(options) кроме единицы и почему?

![Снимок экрана от 2020-07-19 22-21-27](https://user-images.githubusercontent.com/38564412/87883172-4b4e5880-ca0e-11ea-896c-19ace88d4bcc.png)

**Comment by MorganaLF** [comment]
По-моему, эти два if-a почти идентичны, код дублируется:

![Снимок экрана от 2020-07-19 22-23-44](https://user-images.githubusercontent.com/38564412/87883223-a1230080-ca0e-11ea-8b66-107540ad8132.png)

**Comment by MorganaLF** [comment]
Мне кажется, "длина шкалы" для модели не очень подходящее название переменной, все-таки элемент шкалы - это элемент вьюхи. Может, "диапазон" назвать или как-то так?

![Снимок экрана от 2020-07-19 22-25-58](https://user-images.githubusercontent.com/38564412/87883296-0e369600-ca0f-11ea-9f2a-7d141a6b3ea1.png)

**Comment by MorganaLF** [comment]
Еще вопрос: что такое интервал и почему он  на два делится?

**Comment by RomKmeister** [comment]
> Но тут что-то вообще интересное происходит: если убрать первое задисейбленное правило, линтер ничего не подсвечивает, хотя последний метод calculateRatios должен подсветиться.

Я задисейблил правило class-methods-use-this на уровне всего линтера, а здесь просто забыл удалить, также как и второе, которое относилось к методам ModelCorrection

> А что здесь за странная проверка, какая длина может быть у Object.keys(options) кроме единицы и почему?

Если используется сеттер плагина, то переданные опции, объединяются с текущими, и все соотношения проверяются снова. Мне показалось так проще, чем делать проверки в зависимости от того, что за опции изменены.

> Еще вопрос: что такое интервал и почему он на два делится?

Это чтобы определить какой ползунок должен двигаться при клике на шкалу. Расстояние между ними делится пополам, в одной половине двигается первый ползунок, во второй другой.

**Comment by MorganaLF** [comment]
> Я задисейблил правило class-methods-use-this на уровне всего линтера, а здесь просто забыл удалить, также как и второе, которое относилось к методам ModelCorrection

`class-methods-use-this` еще ладно (хотя иногда это полезно для того, чтобы подумать, не стоит ли сделать метод статическим или вынести его куда-то в хелперы), но вот `no-param-reassign` точно не надо дисейблить на уровне всего проекта) И желательно вообще нигде не дисейблить)

**Comment by MorganaLF** [comment]
> Это чтобы определить какой ползунок должен двигаться при клике на шкалу. Расстояние между ними делится пополам, в одной половине двигается первый ползунок, во второй другой.

Тогда надо уточнить в названии, что за интервал, потому что с первого взгляда по названию кажется, будто это какой-то параметр, относящийся к настройкам слайдера.
