### ISSUE TITLE
ModelCorrection

### ISSUE THREAD

**Issue by MorganaLF** [RomKmeister/Slider#12]
А зачем тут спредится `step`? Можно же просто `step` написать? И ниже много где еще так делается:

![Снимок экрана от 2020-07-19 22-30-27](https://user-images.githubusercontent.com/38564412/87883372-93ba4600-ca0f-11ea-895a-32c0c53df6d2.png)

И еще момент: мутации не очень хорошая практика, лучше сохранить параметры в переменную. Как-нибудь так: `const correctedStep = step < 1 ? 1 : step;`

По поводу мутаций надо по всему проекту проверить. Это может приводить к разным багам.

**Comment by MorganaLF** [comment]
Что такое `isNeedShortStep`?) Звучит странно)

![Снимок экрана от 2020-07-19 22-39-03](https://user-images.githubusercontent.com/38564412/87883535-ba2cb100-ca10-11ea-9958-a458f61382db.png)

**Comment by MorganaLF** [comment]
Вот тут по названию не понятно, что именно корректируется. Что такое ConfusedValues? 

![Снимок экрана от 2020-07-19 22-41-43](https://user-images.githubusercontent.com/38564412/87883583-227b9280-ca11-11ea-89d5-c14b6b025839.png)

**Comment by MorganaLF** [comment]
Название `setModelParameters` не описывает, что делает этот метод. По названию кажется, что он просто задает какие-то параметры, а на деле он еще и возвращает их. Из-за чего неочевидным выглядит вот такое использование:

![Снимок экрана от 2020-07-28 17-33-17](https://user-images.githubusercontent.com/38564412/88679764-71ec4d80-d0f8-11ea-8c48-f490212dd1fd.png)

Учитывая то, что метод делает две задачи, возможно, его вообще нужно на два метода разделить.

**Comment by MorganaLF** [comment]
Что такое max1?) В именах переменных нежелательно использовать нумерацию, нужно дать название, отражающее содержание переменной

![Снимок экрана от 2020-07-28 17-38-16](https://user-images.githubusercontent.com/38564412/88680520-4322a700-d0f9-11ea-8a3f-ef2dbeaf62c3.png)

**Comment by MorganaLF** [comment]
Такие длинные строки с кучей условий желательно форматировать - тяжело читается. Тебе даже линтер подсвечивает, что строка длинная. А лучше по возможности и вовсе выносить что-то в переменные:

![Снимок экрана от 2020-07-28 17-40-49](https://user-images.githubusercontent.com/38564412/88680845-998fe580-d0f9-11ea-8a27-e7372c36385c.png)

**Comment by RomKmeister** [comment]
> Название setModelParameters не описывает, что делает этот метод.

> Учитывая то, что метод делает две задачи, возможно, его вообще нужно на два метода разделить.

Может назвать его createOptions? Он ведь проверяет корректность введенных данных, преобразуя их, и рассчитывает дополнительные значения для последующей работы.

**Comment by MorganaLF** [comment]
> Может назвать его createOptions? Он ведь проверяет корректность введенных данных, преобразуя их, и рассчитывает дополнительные значения для последующей работы.

createOptions все равно не подразумевает, что метод что-то возвращает)
