### ISSUE TITLE
HandleView

### ISSUE THREAD

**Issue by MorganaLF** [RomKmeister/Slider#14]
Имя переменной `findClosest` странное. да и тут вообще непонятно, какой смысл было выделять `event.target` в отдельную переменную:

![Снимок экрана от 2020-07-19 22-53-38](https://user-images.githubusercontent.com/38564412/87883823-b4d06600-ca12-11ea-9262-1e0e5a120ee6.png)

`this.target` тоже непонятное название. И чем отличается `this.target` от` this.element`? Из названий должно быть понятно

**Comment by MorganaLF** [comment]
Почему в классе бегунка появляется метод, касающийся двух бегунков сразу? Мне кажется, он уже в опциях сверху должен сразу получить свое `ratio`, а не разбираться, `firstValueRatio` это или `secondValueRatio`.

![Снимок экрана от 2020-07-19 22-58-17](https://user-images.githubusercontent.com/38564412/87883913-5b1c6b80-ca13-11ea-92ef-22b6b68864ea.png)

**Comment by MorganaLF** [comment]
Вот здесь не совсем понятно, что происходит, но такое ощущение, что это тоже что-то про взаимодействие двух бегунков:

![Снимок экрана от 2020-07-19 22-59-18](https://user-images.githubusercontent.com/38564412/87883949-95860880-ca13-11ea-9b75-1d2a791efc2a.png)

**Comment by RomKmeister** [comment]
По ошибке закоммитил исправления в 13-м ишью

**Comment by MorganaLF** [comment]
Чтобы не мучиться с контекстами, проще либо поставить декоратор типа `@bind`, либо использовать синтаксис полей классов ES7, типа такого:

```
handleDocumentClick = () => {
   //
}
```

![Снимок экрана от 2020-07-28 18-25-58](https://user-images.githubusercontent.com/38564412/88687127-8a606600-d100-11ea-96da-786ade6bdb08.png)

**Comment by MorganaLF** [comment]
handle handle) Надо как-то по-другому назвать

![Снимок экрана от 2020-07-28 18-31-38](https://user-images.githubusercontent.com/38564412/88687380-dc08f080-d100-11ea-8965-fb8be38f8457.png)

**Comment by MorganaLF** [comment]
Почему здесь `newOptions`? Разве это опции?

И почему событие называется` 'handlerChanged'`? Во-первых, у тебя во всех остальных местах он называется `handle`, а во-вторых, что происходит в этот момент? По идее, handle двигается, а не меняется. Это и должно отражать имя события. Или еще можно сказать, что меняется его позиция.

![Снимок экрана от 2020-07-28 18-34-50](https://user-images.githubusercontent.com/38564412/88687878-7832f780-d101-11ea-8783-c47d936e7cf7.png)

**Comment by MorganaLF** [comment]
Handle, не handles

![Снимок экрана от 2020-07-28 18-39-26](https://user-images.githubusercontent.com/38564412/88688154-b6301b80-d101-11ea-9b63-cd731baee551.png)

**Comment by MorganaLF** [comment]
Почему эни?)

![Снимок экрана от 2020-07-28 18-41-07](https://user-images.githubusercontent.com/38564412/88688406-f7283000-d101-11ea-9c96-62234cc765d5.png)
