### ISSUE TITLE
ScaleView

### ISSUE THREAD

**Issue by MorganaLF** [RomKmeister/Slider#17]
Снова в именах используется контекст, который и так ясен: мы ведь находимся в классе ScaleView:

![Снимок экрана от 2020-07-28 18-48-00](https://user-images.githubusercontent.com/38564412/88689275-f643ce00-d102-11ea-9908-a1ebcda4452d.png)

И вообще, в этом методе не только установка параметров происходит:

![Снимок экрана от 2020-07-28 18-51-17](https://user-images.githubusercontent.com/38564412/88689611-5b97bf00-d103-11ea-97e4-3ab0b078d27c.png)

**Comment by MorganaLF** [comment]
Появился вопрос: у тебя отключение/включение шкалы и подсказок осуществляется просто путем css? То есть, если шкала не нужна, ее html элемент все равно отрисован, но просто скрыт стилями?

![Снимок экрана от 2020-07-28 18-54-20](https://user-images.githubusercontent.com/38564412/88690092-f7292f80-d103-11ea-8187-fdafe876ec76.png)

**Comment by RomKmeister** [comment]
> Два абсолютно идентичных метода

Я тут запутался в стандартах, именование обработчиков должно быть по шаблону `handleElementNameEventName`, element Name разный, а остальное одинаково, что делать?

> Появился вопрос: у тебя отключение/включение шкалы и подсказок осуществляется просто путем css? То есть, если шкала не нужна, ее html элемент все равно отрисован, но просто скрыт стилями?

Да, все так

**Comment by MorganaLF** [comment]
> Я тут запутался в стандартах, именование обработчиков должно быть по шаблону handleElementNameEventName, element Name разный, а остальное одинаково, что делать?

Повторяющийся код стоит выносить в отдельный метод, который можно потом вызывать внутри обработчиков. То есть в данном случае внутри обработчиков у тебя кроме вызова этого метода больше ничего не будет.

**Comment by MorganaLF** [comment]
> Да, все так

Это не очень хорошо) То есть получается, пользователю не нужна никакая шкала, но она внезапно обнаруживается в html-коде.

**Comment by RomKmeister** [comment]
> Это не очень хорошо) То есть получается, пользователю не нужна никакая шкала, и он предполагает, что её нет, но она внезапно обнаруживается в html-коде.

Я исходил из того, что было бы проще скрыть только главный элемент, а не удалять все элементы, кроме того если шкала снова понадобился ее не нужно будет заново считать и отрисовывать.
Второй момент это то, что мне всегда нужен один отрисованный элемент, чтобы рассчитать сколько шагов будет в шкале.   Можно изменить шрифт в цсс, но цифры не свалятся в кучу, потому что будет взято значение элемента со страницы.

И еще у меня такое же поведение у второго ползунка, он тоже всегда есть, со всеми параметрами, просто может быть скрыт.
И подсказки всегда есть у обоих ползунков...

**Comment by MorganaLF** [comment]
> Я исходил из того, что было бы проще скрыть только главный элемент, а не удалять все элементы, кроме того если шкала снова понадобился ее не нужно будет заново считать и отрисовывать.

Но в реальной жизни навряд ли в приложении, в котором бы использовался твой плагин, в нем бесконечно бы включались/отключались шкала и бегунки, одиночный слайдер или интервал. Мне не кажется, что это оправдано.

Но вот обнаружив какие-то лишние элементы в html, которые там не предполагались, пользователь будет вряд ли приятно удивлен. Это больше похоже на какой-то костыль.

> Второй момент это то, что мне всегда нужен один отрисованный элемент, чтобы рассчитать сколько шагов будет в шкале. Можно изменить шрифт в цсс, но цифры не свалятся в кучу, потому что будет взято значение элемента со страницы.

Здесь не поняла, какой элемент тебе нужен, чтобы рассчитать количество шагов?

**Comment by RomKmeister** [comment]
> Но вот обнаружив какие-то лишние элементы в html, которые там не предполагались, пользователь будет вряд ли приятно удивлен. Это больше похоже на какой-то костыль.

Получается слайдер должен изначально включать полоску шкалы и один ползунок, а остальное должно создаваться в js по необходимости?

Не будет ли это противоречить пункту стандартов:
> Все, что может быть написано на чистых html+css в рамках тех свойств, что дают заявленные браузеры - должно быть написано без применения JS

**Comment by MorganaLF** [comment]
> Не будет ли это противоречить пункту стандартов

Но ты ведь не можешь на чистом html динамически менять его содержимое? С этим может справиться только js.

> Получается слайдер должен изначально включать полоску шкалы и один ползунок, а остальное должно создаваться в js по необходимости?

Смотря какие опции ему заданы изначально. Вью должна отрисовывать или нет шкалу (ползунок) в зависимости от того, что указано в модели.

Теоретически у тебя в приложении могут отрисовываться по условию целые компоненты и даже большие части страницы, ты же не будешь их скрывать при помощи `display: none`?)
