### ISSUE TITLE
Бизнес логика

### ISSUE THREAD

**Issue by prodderman** [RomKmeister/Slider#24]
Должна ли модель знать о том, что слайдер вертикальный или горизонтальный, или видна шкала или нет? Эти данные никак не участвуют в расчетах и нужны только во вьюхе. Можешь обосновать, почему они должны быть в модели?

**Comment by RomKmeister** [comment]
Мне показалось, что так как модель включает и бизнес-логику, и данные, то она должна хранить в себе состояния, которые описывают вид слайдера. Слайдер может быть горизонтальным или вертикальным, но что-то из этого обязательно должно быть. С этим состоянием в модели не происходит расчетов, но оно там хранится. Аналогично с другими вьюшными параметрами.
Кроме того мне кажется, что передавать внутри приложения один объект с параметрами проще, чем получить список опций от пользователя, а затем где-то внутри приложения писать код для разбивки этого объекта для модели и для вью.
Ну и пользователь сам конечно ничего делить не должен, просто написал один список параметров — и работает.

**Comment by prodderman** [comment]
А почему знания о вертикальности или горизонтальности это бизнес логика?)
